Compose:
  active: true

complexity:
  LongParameterList:
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/sharedTest/**"
      - "**/commonTest/**"
      - "**/jvmTest/**"
      - "**/androidUnitTest/**"
      - "**/androidInstrumentedTest/**"
